# Generated by Django 3.2.4 on 2021-07-10 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_alter_article_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='uid',
            new_name='user',
        ),
    ]
