# Generated by Django 3.2.4 on 2021-07-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_rename_uid_article_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='uid_id',
            field=models.BigIntegerField(default=False),
        ),
    ]
