# Generated by Django 3.2.4 on 2021-07-31 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0005_auto_20210728_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
