# Generated by Django 3.2.4 on 2021-07-10 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0006_alter_article_uid_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='uid_id',
            new_name='uid',
        ),
    ]
