# Generated by Django 3.2.4 on 2021-07-11 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0007_rename_uid_id_article_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='uid',
        ),
    ]
