# Generated by Django 3.2.4 on 2021-08-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0007_auto_20210802_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='likes',
            field=models.BigIntegerField(default=0),
        ),
    ]
