# Generated by Django 3.2.4 on 2021-07-11 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0009_auto_20210711_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='author',
            new_name='author_id',
        ),
    ]
