# Generated by Django 3.2.4 on 2021-08-24 11:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Post', '0009_auto_20210823_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='likes',
            field=models.ManyToManyField(default=None, related_name='like', to=settings.AUTH_USER_MODEL),
        ),
    ]
