# Generated by Django 3.2.4 on 2021-07-11 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0010_rename_author_article_author_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='author_id',
            new_name='author',
        ),
    ]
