# Generated by Django 3.2.4 on 2021-09-20 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_userprofile_bio'),
        ('Post', '0012_article_cover_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='require_mask',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
    ]
