# Generated by Django 3.2.4 on 2021-09-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0013_auto_20210920_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='twenty_one_plus',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
