# Generated by Django 3.2.4 on 2021-09-27 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0014_article_twenty_one_plus'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='latitude',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='longitude',
            field=models.BigIntegerField(null=True),
        ),
    ]
