# Generated by Django 3.2.4 on 2021-09-27 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0015_auto_20210926_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='latitude',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='longitude',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
