# Generated by Django 3.2.4 on 2021-07-10 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='uid',
        ),
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.BigIntegerField(default=False, primary_key=True, serialize=False),
        ),
    ]
