# Generated by Django 3.2.4 on 2021-08-02 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='accounts.user', verbose_name='user')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('bio', models.TextField()),
                ('avatar', models.ImageField(upload_to='media/profilePictures')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='token',
        ),
    ]
