# Generated by Django 3.2.4 on 2021-08-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210802_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='media/profilePictures/default-avatar.png', upload_to='media/profilePictures'),
        ),
    ]
