# Generated by Django 3.2.4 on 2021-08-08 21:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_userdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='userData',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
