# Generated by Django 3.2.4 on 2021-08-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_followerrelation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followerrelation',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddConstraint(
            model_name='followerrelation',
            constraint=models.UniqueConstraint(fields=('user', 'profile'), name='unique_followers'),
        ),
    ]
