# Generated by Django 3.2.4 on 2021-09-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210810_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='instagramID',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
