# Generated by Django 3.2.4 on 2021-09-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userprofile_instagramid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='linkedinID',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='snapchatID',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
