# Generated by Django 3.2.4 on 2021-09-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.CharField(default='00000000', max_length=8),
        ),
    ]
