# Generated by Django 3.2.4 on 2021-09-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='/media/profilePictures/default-avatar.png', upload_to='media/profilePictures'),
        ),
    ]
