# Generated by Django 3.2.4 on 2021-09-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hasAgreedTos',
            field=models.BooleanField(default=False),
        ),
    ]
