# Generated by Django 3.2.4 on 2021-09-24 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_user_hasagreedtos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='hasAgreedTos',
            new_name='has_agreed_tos',
        ),
    ]
